# content will be available in a dictionary format

training_pipeline_config:
  # name for the entire pipeline
  pipeline_name: housing
  # whenever this entire pipeline will run, every component is going to generate some artifact,
  # so it is the location where that artifact will be stored
  artifact_dir: artifact

# these info. is from the data ingestion named tuple

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml

model_evaluation_config: #contains best model location which is in production already
  model_evaluation_file_name: model_evaluation.yaml
  
model_pusher_config:
  model_export_dir: saved_models

